<?xml version="1.0"?>
<robot name="mounted_d435i" xmlns:xacro="http://www.ros.org/wiki/xacro">
	<xacro:include filename="$(find robot_description)/urdf/_d435i.urdf.xacro"/>

	<xacro:macro name="mounted_d435i" params="parent *origin name:=camera use_nominal_extrinsics:=false mount_mesh_scale:=1.0 mount_mesh_x:=0.04073 mount_mesh_y:=0.1082 mount_mesh_z:=0.05081 mount_collision_x:=0.04073 mount_collision_y:=0.1082 mount_collision_z:=0.05081">
		<xacro:property name="mount_collision_padding" value="0.005" />
		<link name="camera_mount_base">
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
					<mesh filename="file://$(find robot_description)/meshes/camera_mount.stl" scale="${mount_mesh_scale} ${mount_mesh_scale} ${mount_mesh_scale}" />
				</geometry>
				<material name="mount_gray">
					<color rgba="0.6 0.6 0.6 1.0" />
				</material>
			</visual>
		</link>
		<joint name="camera_mount_base_joint" type="fixed">
			<xacro:insert_block name="origin" />
			<parent link="${parent}" />
			<child link="camera_mount_base" />
		</joint>

		<link name="${name}_mount">
			<collision>
				<origin xyz="0.006 0.005 ${-mount_collision_padding + (mount_collision_z + 2 * mount_collision_padding) / 2 - 0.0145}" rpy="0 0 0" />
				<geometry>
					<box size="${mount_collision_x + 2 * mount_collision_padding} ${mount_collision_y + 2 * mount_collision_padding} ${mount_collision_z + 2 * mount_collision_padding}" />
				</geometry>
			</collision>
		</link>
		<joint name="${name}_mount_top" type="fixed">
			<parent link="camera_mount_base" />
			<child link="${name}_mount" />
            <origin xyz="0 0 0.0145" rpy="0 0 0" />
		</joint>

		<xacro:sensor_d435i parent="${name}_mount" name="${name}" use_nominal_extrinsics="${use_nominal_extrinsics}">
			<origin xyz="0.006 0 0" rpy="0 0 0" /> // Not sure of exact offset, delta x from central hole on camera mount to center of camera screw mount
		</xacro:sensor_d435i>
	</xacro:macro>
</robot>